# Author: Benjamin Oakes <hello@benjaminoakes.com>

task 'default' => ['Point.class', 'Main.class'] do
	sh 'java Main'
end

file 'Main.class' => ['Main.java'] do
	sh 'javac Main.java'
end

file 'Point.class' => ['Point.java'] do
	sh 'javac Point.java'
end

file 'Person.class' => ['Person.java'] do
	sh 'javac Person.java'
end

